### ISSUE TITLE
Cannot read property 'offsetHeight' of null

### ISSUE THREAD

**Issue by murugaratham** [marnusw/react-css-transition-replace#4]
Hi, i am getting the error: Cannot read property 'offsetHeight' of null, sometimes. I have a <div/> element that is doing the following:

```
<ReactCSSTransitionReplace transitionName="fade-wait" 
                                     overflowHidden={false}
                                     transitionEnterTimeout={Constants.Feed.FadeTransitionInterval.Enter} 
                                     transitionLeaveTimeout={Constants.Feed.FadeTransitionInterval.Leave}>
            <MyElement key={this.state.key} data={data} />
</ReactCSSTransitionReplace>
```

In chrome:
```
 this.setState({
        nextChild: nextChild,
        height: _reactDom2['default'].findDOMNode(this.refs.curr).offsetHeight //<-- null
      }, function () {
        return _this2.setState({
          height: _reactDom2['default'].findDOMNode(_this2.refs.next).offsetHeight
        });
      });
```

I would like to narrow down the error for you, but it seems to happen very unpredicatbly, as i have an array of 15 objects and using setInterval, i'm replacing the element every 5s or so, when i idle for 20mins or so, the null exception occurs but in the timespan, it would have rotated at least a couple hundred times. Is it due to garbage collection?

**Comment by marnusw** [comment]
The issue is that there is no `currentChild` component/element on the DOM to get the height from at that time. As to *why* there is no current child I can't say yet, since at first glance there should always be one. Garbage collection might be the culprit, but I'll investigate this further.

You did, however, point out through this that the component does not work correctly when it has no children, which I think it should. I've started working on a fix for that.

**Comment by marnusw** [comment]
@murugaratham, I have yet to reproduce your error on my side, but what I did do is add support for having no children on the `ReactCSSTransitionReplace` component. Would you mind installing `marnusw/react-css-transition-replace#noChild` in your project and seeing whether you still get the error?

**Comment by murugaratham** [comment]
Sure, will update after testing, thanks for prompt response

**Comment by marnusw** [comment]
I've released these changes as `v1.0.1` and have subsequently released `v1.1.0` as well. I did some reasonable testing and am pretty sure I didn't break anything, so even if the new version still doesn't solve your issue we should at least not be any worse off. I'll close this for now, but do let me know if this problem persists.

**Comment by murugaratham** [comment]
Many thanks 

Sent from my iPhone, please excuse brevity.
Regards,
Gary

On 25 Nov 2015, at 05:35, Marnus Weststrate <notifications@github.com> wrote:

I've released these changes as v1.0.1 and have subsequently released v1.1.0 as well. I did some reasonable testing and am pretty sure I didn't break anything, so even if the new version still doesn't solve your issue we should at least not be any worse off. I'll close this for now, but do let me know if this problem persists.

―

**Comment by nitrog7** [comment]
Height is still getting stuck at 0. My situation is when the parent is using the following styles:
position: absolute;
display: flex;
flex: 1;
top: 0;
bottom: 0;
left: 0;
right: 0;

To quickly solve the problem, I have to add some "important" flags:
.animation-height {
    position: absolute !important;
    display: flex !important;
    flex: 1;
    height: auto !important;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    transition: 0.1s ease-out;
  }

Is there a way to disable the use of the height if we don't need it? Or to adjust the styles so we don't have the important flags?

Thanks!
